version: '3'

networks:
    main:
    webgateway:
        driver: bridge
    web:
        external:
            name: traefik_webgateway
volumes:
    config:
        driver: local-persist
        driver_opts:
            mountpoint: /data/config
    torrents:
        driver: local-persist
        driver_opts:
            mountpoint: /data/torrents

services:
    # frontend:
    #     image: fromenje/seedbox:frontend
    #     build: Dockerfiles/frontend
    #     restart: always
    #     networks:
    #         - main
    #     ports:
    #         - "80:80"
    #         - "443:443"
    #     volumes:
    #         - config:/config
    #     env_file:
    #         - config

    traefik:
        image: traefik
        container_name: traefik
        restart: always
        networks:
            - webgateway
        command: --acme.email=${ACME_MAIL} --docker.domain=${TRAEFIK_DOMAIN}
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/traefik.toml
            - /opt/traefik/acme.json:/acme.json

    deluge:
        image: fromenje/seedbox:deluge
        build: Dockerfiles/deluge
        restart: always
        networks:
            - main
        volumes:
            - torrents:/torrents
            - config:/config
        env_file:
            - config

    h5ai:
        image: fromenje/seedbox:h5ai
        build: Dockerfiles/h5ai
        restart: always
        networks:
            - main
        volumes:
            - torrents:/torrents
            - config:/config
        env_file:
            - config

    owncloud:
        image: owncloud:latest
        restart: always
        volumes:
            - torrents:/var/www/html/data/admin/files
        networks:
            - main
        ports:
            - "7474:80"

    plex:
        image: fromenje/seedbox:plex
        build: Dockerfiles/plex
        restart: always
        networks:
            - main
        ports:
            - "32400:32400"
        volumes:
            - config:/config
            - torrents:/torrents
        env_file:
            - config

    sonarr:
        image: fromenje/seedbox:sonarr
        build: Dockerfiles/sonarr
        restart: always
        networks:
            - main
        volumes:
            - config:/config
            - torrents:/torrents
        environment:
            - TZ=Europe/Paris

    radarr:
        image: fromenje/seedbox:radarr
        build: Dockerfiles/radarr
        restart: always
        networks:
            - main
        volumes:
            - config:/config
            - torrents:/torrents
        env_file:
            - config
        environment:
            - PGID=0
            - PUID=0
            - TZ=Europe/Paris

    organizr:
        image: lsiocommunity/organizr
        restart: always
        networks:
            - main
        volumes:
            - config:/config
        environment:
            - PGID=33
            - PUID=33
            - TZ=Europe/Paris

    portainer:
        image: portainer/portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - web
        command: --admin-password ${PORTAINER_ADMIN_PASSWORD} --host=unix:///var/run/docker.sock
        labels:
            - 'traefik.backend=portainer'
            - 'traefik.port=9000'
            - 'traefik.frontend.rule=Host:portainer.${TRAEFIK_DOMAIN}'
            - 'traefik.enable=true'

