version: '3'

networks:
    main:

volumes:
    config:
        driver: local
    torrents:
        driver: local

services:
    frontend:
        image: fromenje/seedbox:frontend
        build: Dockerfiles/frontend
        restart: always
        networks:
            - main
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - config:/config
        env_file:
            - config

    rtorrent:
        image: fromenje/seedbox:rtorrent
        build: Dockerfiles/rtorrent
        restart: always
        networks:
            - main
        ports:
            - "49161:49161"
            - "49161:49161/udp"
            - "6881:6881/udp"
        volumes:
            - config:/config
            - torrents:/torrents

    deluge:
        image: fromenje/seedbox:deluge
        build: Dockerfiles/deluge
        restart: always
        networks:
            - main
        ports:
            - "8112:8112"
            - "58846:58846"
            - "53160:53160"
            - "53160:53160/udp"
        volumes:
            - torrents:/torrents
            - config:/config
        env_file:
            - config

    h5ai:
        image: fromenje/seedbox:h5ai
        build: Dockerfiles/h5ai
        restart: always
        networks:
            - main
        ports:
            - "12333:80"
        volumes:
            - torrents:/var/www
            - config:/config
        env_file:
            - config

    plex:
        image: fromenje/seedbox:plex
        build: Dockerfiles/plex
        restart: always
        networks:
            - main
        ports:
            - "32400:32400"
        volumes:
            - config:/config
            - torrents:/torrents
        env_file:
            - config

    sonarr:
        image: fromenje/seedbox:sonarr
        build: Dockerfiles/sonarr
        restart: always
        networks:
            - main
        volumes:
            - config:/config
            - torrents:/torrents
