api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik-network"
    exposedByDefault: false # Only expose explicitly enabled containers
  file:
    filename: /etc/traefik/file-provider.yml

entryPoints:
  insecure:
    address: ":80"
  secure:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      storage: /config/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: insecure
