version: '3'

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    env_file:
     - ./traefik.env
    networks:
      - webgateway
    command: --acme.email=${ACME_MAIL} --docker.domain=${TRAEFIK_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json

networks:
  webgateway:
    driver: bridge
