api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik-network"
    exposedByDefault: false # Only expose explicitly enabled containers
  file:
    directory: /etc/traefik/custom
    watch: true

entryPoints:
  insecure:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: secure
          scheme: https
  secure:
    address: ":443"
    http:
      tls:
        certResolver: le
      middlewares:
      - security-headers@file

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  le:
    acme:
      storage: /config/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: insecure
