services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - torrents:/torrents
      - configdeluge:/config
      - downloads:/downloads
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    # Traefik labels are in Gluetun YAML as deluge must be accessed via Gluetun

volumes:
  configdeluge: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/deluge