services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    restart: always
    volumes:
      - configheimdall:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.heimdall.middlewares=common-auth@file"

volumes:
  configheimdall:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/heimdall