services:
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - configjdownloader:/config
      - downloads:/output
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=${TZ}
    # Traefik routing rules are defined in the samples/ directory and applied automatically when this service is enabled

volumes:
  configjdownloader:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/jdownloader