services:
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    restart: always
    volumes:
      - configkavita:/kavita/config
      - torrents:/torrents
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    # Wait for https://github.com/Kareadita/Kavita/issues/301 to be resolved
    #user: "${PUID}:${PGID}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.rule=Host(`kavita.${TRAEFIK_DOMAIN}`)"

volumes:
  configkavita: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/kavita