services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: always
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
    volumes:
      - configplex:/config
      - torrents:/torrents
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - VERSION=latest

volumes:
  configplex:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/Plex