services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - configsyncthing:/config
      - torrents:/torrents
    # ports:
    #   #- 8384:8384
    #   - 22000:22000/tcp
    #   - 22000:22000/udp
    #   - 21027:21027/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.syncthing.middlewares=common-auth@file"
      - "traefik.http.routers.syncthing.service=syncthing"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.http.routers.synchro.rule=Host(`synchro.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.synchro.service=synchro"
      - "traefik.http.services.synchro.loadbalancer.server.port=22000"

volumes:
  configsyncthing: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/configsyncthing